repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: detect-private-key
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
    -   id: mypy
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]
# -   repo: https://github.com/pre-commit/mirrors-isort
#     rev: 'v5.10.1'
#     hooks:
#     -   id: isort
# -   repo: local
#     hooks:
#     -   id: pytest
#         name: pytest
#         entry: bash -c 'cd chatbot && source ./venv/bin/activate && pytest -p no:warnings .'
#         language: system
#         files: '.*\.py$'
#         stages: [commit]
#         pass_filenames: false
#         always_run: true
